spring.application.name=JishuHozen

spring.datasource.url=jdbc:postgresql://db.xdygbwzhtdbknjhuddhz.supabase.co:5432/postgres?user=postgres&password=z5TrF5Y3yDd8swLz
spring.datasource.username=postgres
spring.datasource.password=z5TrF5Y3yDd8swLz

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=1608
jwt.expiration=864000
jwt.secret=Rx4PmASMnyuyiyr*&*loHRfkucJT7C0cwpfXVHsv+isxqF84/GygMMxg=
server.forward-headers-strategy=framework