spring.application.name=JishuHozen
spring.datasource.url=jdbc:postgresql://ep-broad-fire-aohzu6cr-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3MGE4ZypxhLi
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=1608
jwt.expiration=864000
jwt.secret=Rx4PmASMnyuyiyr*&*loHRfkJT7C0cwpfXVHsv+isxqF84/GygMMxg=
server.forward-headers-strategy=framework