spring.application.name=JishuHozen

spring.datasource.url=jdbc:postgresql://db.xdygbwzhtdbknjhuddhz.supabase.co:5432/postgres?user=postgres&password=KSFqy4ibgMv0rVfk
spring.datasource.username=postgres
spring.datasource.password=KSFqy4ibgMv0rVfk
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=1608
jwt.expiration=864000
jwt.secret=Rx4PmASMnyuyiyr*&*loHRfkJT7C0cwpfXVHsv+isxqF84/GygMMxg=
server.forward-headers-strategy=framework